version: '3'
services:
    conveycqrs:
      image: conveycqrs:latest
      build:
          context: .
          dockerfile: convey-cqrs/Dockerfile
      ports:
          - '6000:80'
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
    postgres:
      container_name: postgres
      image: postgres:alpine
      environment:
        PGDATA: /data/postgres
        POSTGRES_PASSWORD: password
      volumes:
        - postgres:/data/postgres
      ports:
        - 5432:5432
      restart: unless-stopped
    flyway:
      image: flyway/flyway
      command: -url=jdbc:postgresql://postgres/ -user=postgres -password=password migrate
      volumes:
        - ./flyway/sql:/flyway/sql
      depends_on:
        - postgres
    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: password
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - 5050:80
      restart: unless-stopped
volumes:
    postgres:
    pgadmin: