version: '3'
services:
    conveycqrs:
        image: 'conveycqrs:latest'
        build:
            context: .
            dockerfile: convey-cqrs/Dockerfile
        ports:
            - '5000:80'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development